language: python
python:
- "3.4"
install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-mark hold apt apt-utils cron dpkg dpkg-dev iptables login mount openssh-server
  postgresql* ssh sudo resolvconf rsyslog sysvinit* ubuntu-minimal upstart util-linux
- sudo apt-get install -y coreutils g++-4.8 libmpfr-dev ruby2.0  wget
before_script:
- cd cpp
- g++-4.8 -std=c++11 -Wall -O3 calc.cpp -lmpfr -lgmp
- echo "b1ef9dd187215b9997a060588f66d56b08e278b8  pi-sample.txt" > pi-sample.txt.sha1
- wget https://gist.githubusercontent.com/z2s8/d93faee96fb08fb6e217/raw/05f9a6798327f704a45f5115b741feb5a771016b/pi-sample.txt
- sha1sum -c pi-sample.txt.sha1
script:
- time ./a.out > ./pi-calced-cpp.txt
- time python3 ../py3/calc.py > ./pi-calced-py3.txt
- time ruby2.0 ../rb/calc.rb > ./pi-calced-rb.txt
after_script:
- python ../digit_precision.py pi-sample.txt pi-calced-cpp.txt
- python ../digit_precision.py pi-sample.txt pi-calced-py3.txt
- python ../digit_precision.py pi-sample.txt pi-calced-rb.txt
notifications:
  email: false
  slack:
    secure: fvXMXQFfKDt8+mX5eIk+T2Yg0LBFCOkA3H/clM/O2uDa74Arl4FtVWjs61jXHCLs182Kx3M6Zty4NgwunmqTB+erw3vY/RAmN2WExHKJI4RaGSln1rzIQ3WAcm8lSH/PoodU549AOG3JUxrnmZo1rYpJyD6cqby0vIfzF72hki8=
    on_success: change
    on_failure: change
